# Generated by Django 6.0 on 2026-01-05 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
                ('object_repr', models.CharField()),
                ('action', models.CharField(choices=[('c', 'create'), ('u', 'update'), ('d', 'delete')])),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('action__in', ['c', 'u', 'd'])), name='Action validation')],
            },
        ),
    ]
