# Generated by Django 6.0 on 2026-01-05 04:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('history', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='historyentry',
            name='Action validation',
        ),
        migrations.AddConstraint(
            model_name='historyentry',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['c', 'u', 'd'])), name="\n                Action is not valid.\n                Valid actions are: ['c', 'u', 'd']"),
        ),
    ]
