# Generated by Django 6.0 on 2026-01-05 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('history', '0003_remove_historyentry__action_is_not_valid_valid_actions_are_c_u_d__and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='historyentry',
            name="\n                Action validation\n                Valid actions are: ['c', 'u', 'd']",
        ),
        migrations.AddConstraint(
            model_name='historyentry',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['c', 'u', 'd'])), name="Action validation\n                Valid actions are: ['c', 'u', 'd']"),
        ),
    ]
