# Generated by Django 6.0 on 2026-01-05 07:05

import django_object_history.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_alter_historyentry_changed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField()),
            ],
            bases=(django_object_history.mixins.TrackedModelMixin, models.Model),
        ),
    ]
